spring:
  datasource:
    username:root
    password:yana123
    driver-class-name: com.mysql.jdbc.Driver
    url:jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC